spring: 
  application:
    name: zeus

  http:
    clients:
      connect-timeout: 30s
      read-timeout: 30s

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true